/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GroupGroupIdIndexImport } from './routes/group/$groupId/index'
import { Route as GroupGroupIdTransactionsNewImport } from './routes/group/$groupId/transactions/new'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GroupGroupIdIndexRoute = GroupGroupIdIndexImport.update({
  id: '/group/$groupId/',
  path: '/group/$groupId/',
  getParentRoute: () => rootRoute,
} as any)

const GroupGroupIdTransactionsNewRoute =
  GroupGroupIdTransactionsNewImport.update({
    id: '/group/$groupId/transactions/new',
    path: '/group/$groupId/transactions/new',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/group/$groupId/': {
      id: '/group/$groupId/'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/group/$groupId/transactions/new': {
      id: '/group/$groupId/transactions/new'
      path: '/group/$groupId/transactions/new'
      fullPath: '/group/$groupId/transactions/new'
      preLoaderRoute: typeof GroupGroupIdTransactionsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group/$groupId': typeof GroupGroupIdIndexRoute
  '/group/$groupId/transactions/new': typeof GroupGroupIdTransactionsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group/$groupId': typeof GroupGroupIdIndexRoute
  '/group/$groupId/transactions/new': typeof GroupGroupIdTransactionsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/group/$groupId/': typeof GroupGroupIdIndexRoute
  '/group/$groupId/transactions/new': typeof GroupGroupIdTransactionsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/group/$groupId' | '/group/$groupId/transactions/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/group/$groupId' | '/group/$groupId/transactions/new'
  id: '__root__' | '/' | '/group/$groupId/' | '/group/$groupId/transactions/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupGroupIdIndexRoute: typeof GroupGroupIdIndexRoute
  GroupGroupIdTransactionsNewRoute: typeof GroupGroupIdTransactionsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupGroupIdIndexRoute: GroupGroupIdIndexRoute,
  GroupGroupIdTransactionsNewRoute: GroupGroupIdTransactionsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/group/$groupId/",
        "/group/$groupId/transactions/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/group/$groupId/": {
      "filePath": "group/$groupId/index.tsx"
    },
    "/group/$groupId/transactions/new": {
      "filePath": "group/$groupId/transactions/new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
